### ISSUE TITLE
Problem while auto installing PlatformIO

### ISSUE THREAD

**Issue by SexyDad594** [akaJes/marlin-config#107]
I'm getting this error when I try to autoinstall PlatformIO

[Window Title]
Error

[Main Instruction]
A JavaScript error occurred in the main process

[Content]
Uncaught Exception:
TypeError: Cannot read property 'headers' of undefined
    at Request._callback (C:\Users\Kyriazopoulos.Al\AppData\Local\Programs\marlin-conf\resources\app.asar\node_modules\platformio-node-helpers\lib\index.js:2800:32)
    at self.callback (C:\Users\Kyriazopoulos.Al\AppData\Local\Programs\marlin-conf\resources\app.asar\node_modules\request\request.js:186:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:191:7)
    at Request.onRequestError (C:\Users\Kyriazopoulos.Al\AppData\Local\Programs\marlin-conf\resources\app.asar\node_modules\request\request.js:878:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:191:7)
    at TLSSocket.socketErrorListener (_http_client.js:358:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:191:7)

[OK]

How can I fix this issue?

Best Regards
SexyDad594

**Comment by SexyDad594** [comment]
Damn. Thanks for neglecting me just like my parents did. Not only am I an orphan but also very sexy. You're definetly missing out on my love!
