### ISSUE TITLE
 Windows Installation of marlin conf thru cmd

### ISSUE THREAD

**Issue by BoiPancit** [akaJes/marlin-config#109]
Installing the newest windows version of marlin conf thru cmd and got this. What does that mean? Can anyone please help me, for I don't have any programming background myself. Thank you!

C:\Users\jtapa>npm -g i marlin-conf
npm WARN deprecated rtcmulticonnection-v3@3.4.5: Please use `rtcmulticonnection` instead. i.e. do NOT include `-v3`.
npm WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning ETIMEDOUT: request to https://registry.npmjs.org/bytes failed, reason: connect ETIMEDOUT 104.16.19.35:443
npm WARN registry Using stale data from https://registry.npmjs.org/ due to a request error during revalidation.
C:\Users\jtapa\AppData\Roaming\npm\mctd -> C:\Users\jtapa\AppData\Roaming\npm\node_modules\marlin-conf\bin\mctd
C:\Users\jtapa\AppData\Roaming\npm\mct -> C:\Users\jtapa\AppData\Roaming\npm\node_modules\marlin-conf\bin\mct
npm WARN notsup Unsupported engine for rtcmulticonnection-v3@3.4.5: wanted: {"node":"latest"} (current: {"node":"12.14.1","npm":"6.13.4"})
npm WARN notsup Not compatible with your version of node/npm: rtcmulticonnection-v3@3.4.5

+ marlin-conf@2.10.5
updated 1 package in 2215.65s

**Comment by BoiPancit** [comment]
C:\Users\jtapa\Desktop\New folder>mct
C:\Users\jtapa\AppData\Roaming\npm\node_modules\marlin-conf\node_modules\bindings\bindings.js:96
  throw err
  ^

Error: Could not locate the bindings file. Tried:
 → C:\Users\jtapa\AppData\Roaming\npm\node_modules\marlin-conf\node_modules\serialport\build\serialport.node
 → C:\Users\jtapa\AppData\Roaming\npm\node_modules\marlin-conf\node_modules\serialport\build\Debug\serialport.node
 → C:\Users\jtapa\AppData\Roaming\npm\node_modules\marlin-conf\node_modules\serialport\build\Release\serialport.node
 → C:\Users\jtapa\AppData\Roaming\npm\node_modules\marlin-conf\node_modules\serialport\out\Debug\serialport.node
 → C:\Users\jtapa\AppData\Roaming\npm\node_modules\marlin-conf\node_modules\serialport\Debug\serialport.node
 → C:\Users\jtapa\AppData\Roaming\npm\node_modules\marlin-conf\node_modules\serialport\out\Release\serialport.node
 → C:\Users\jtapa\AppData\Roaming\npm\node_modules\marlin-conf\node_modules\serialport\Release\serialport.node
 → C:\Users\jtapa\AppData\Roaming\npm\node_modules\marlin-conf\node_modules\serialport\build\default\serialport.node
 → C:\Users\jtapa\AppData\Roaming\npm\node_modules\marlin-conf\node_modules\serialport\compiled\12.14.1\win32\x64\serialport.node
    at bindings (C:\Users\jtapa\AppData\Roaming\npm\node_modules\marlin-conf\node_modules\bindings\bindings.js:93:9)
    at Object.<anonymous> (C:\Users\jtapa\AppData\Roaming\npm\node_modules\marlin-conf\node_modules\serialport\lib\bindings\win32.js:2:36)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (C:\Users\jtapa\AppData\Roaming\npm\node_modules\marlin-conf\node_modules\serialport\lib\bindings\auto-detect.js:8:22)
    at Module._compile (internal/modules/cjs/loader.js:955:30) {
  tries: [
    'C:\\Users\\jtapa\\AppData\\Roaming\\npm\\node_modules\\marlin-conf\\node_modules\\serialport\\build\\serialport.node',
    'C:\\Users\\jtapa\\AppData\\Roaming\\npm\\node_modules\\marlin-conf\\node_modules\\serialport\\build\\Debug\\serialport.node',
    'C:\\Users\\jtapa\\AppData\\Roaming\\npm\\node_modules\\marlin-conf\\node_modules\\serialport\\build\\Release\\serialport.node',
    'C:\\Users\\jtapa\\AppData\\Roaming\\npm\\node_modules\\marlin-conf\\node_modules\\serialport\\out\\Debug\\serialport.node',
    'C:\\Users\\jtapa\\AppData\\Roaming\\npm\\node_modules\\marlin-conf\\node_modules\\serialport\\Debug\\serialport.node',
    'C:\\Users\\jtapa\\AppData\\Roaming\\npm\\node_modules\\marlin-conf\\node_modules\\serialport\\out\\Release\\serialport.node',
    'C:\\Users\\jtapa\\AppData\\Roaming\\npm\\node_modules\\marlin-conf\\node_modules\\serialport\\Release\\serialport.node',
    'C:\\Users\\jtapa\\AppData\\Roaming\\npm\\node_modules\\marlin-conf\\node_modules\\serialport\\build\\default\\serialport.node',
    'C:\\Users\\jtapa\\AppData\\Roaming\\npm\\node_modules\\marlin-conf\\node_modules\\serialport\\compiled\\12.14.1\\win32\\x64\\serialport.node'
  ]
}

C:\Users\jtapa\Desktop\New folder>

**Comment by BoiPancit** [comment]
When I use also this binary file to install marlin conf it says.
Error:  Cannot use simple-git in a directory that does not exist.
