### ISSUE TITLE
compile problems.

### ISSUE THREAD

**Issue by RudyBenner** [akaJes/marlin-config#85]
Marlin-config will compile 1.1.9 bugfix 1.1.x but will not compile bugfix 2.0.x
Same packages as above will compile with Arduino 1.8.7
Something is seriously BONKERS. For a while, I thought I had finally snapped.
Have a look.

npacking  [##########################----------]   72%
Unpacking  [##########################----------]   74%
Error: Traceback (most recent call last):
  File "c:\users\rudolfbenner\.platformio\penv\lib\site-packages\platformio\__main__.py", line 120, in main
    cli(None, None, None)
  File "c:\users\rudolfbenner\.platformio\penv\lib\site-packages\click\core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\rudolfbenner\.platformio\penv\lib\site-packages\click\core.py", line 680, in main
    rv = self.invoke(ctx)
  File "c:\users\rudolfbenner\.platformio\penv\lib\site-packages\click\core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\rudolfbenner\.platformio\penv\lib\site-packages\click\core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\rudolfbenner\.platformio\penv\lib\site-packages\click\core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "c:\users\rudolfbenner\.platformio\penv\lib\site-packages\click\decorators.py", line 16, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\users\rudolfbenner\.platformio\penv\lib\site-packages\platformio\commands\run.py", line 107, in cli
    result = (envname, ep.process())
  File "c:\users\rudolfbenner\.platformio\penv\lib\site-packages\platformio\commands\run.py", line 205, in process
    result = self._run()
  File "c:\users\rudolfbenner\.platformio\penv\lib\site-packages\platformio\commands\run.py", line 300, in _run
    self.verbose)
  File "c:\users\rudolfbenner\.platformio\penv\lib\site-packages\platformio\commands\run.py", line 323, in _autoinstall_libdeps
    ctx.invoke(cmd_lib_install, libraries=[lib], silent=not verbose)
  File "c:\users\rudolfbenner\.platformio\penv\lib\site-packages\click\core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "c:\users\rudolfbenner\.platformio\penv\lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "c:\users\rudolfbenner\.platformio\penv\lib\site-packages\platformio\commands\lib.py", line 103, in lib_install
    library, silent=silent, interactive=interactive, force=force)
  File "c:\users\rudolfbenner\.platformio\penv\lib\site-packages\platformio\managers\lib.py", line 354, in install
    force=force)
  File "c:\users\rudolfbenner\.platformio\penv\lib\site-packages\platformio\managers\package.py", line 718, in install
    name, url, requirements, track=True)
  File "c:\users\rudolfbenner\.platformio\penv\lib\site-packages\platformio\managers\package.py", line 444, in _install_from_url
    self.unpack(dlpath, tmp_dir)
  File "c:\users\rudolfbenner\.platformio\penv\lib\site-packages\platformio\managers\package.py", line 219, in unpack
    return fu.unpack(dest_dir, with_progress=with_progress)
  File "c:\users\rudolfbenner\.platformio\penv\lib\site-packages\platformio\unpacker.py", line 117, in unpack
    self._unpacker.extract_item(item, dest_dir)
  File "c:\users\rudolfbenner\.platformio\penv\lib\site-packages\platformio\unpacker.py", line 38, in extract_item
    self._afo.extract(item, dest_dir)
  File "C:\Users\RudolfBenner\.platformio\python27\Lib\zipfile.py", line 1028, in extract
    return self._extract_member(member, path, pwd)
  File "C:\Users\RudolfBenner\.platformio\python27\Lib\zipfile.py", line 1079, in _extract_member
    os.mkdir(targetpath)
WindowsError: [Error 206] The filename or extension is too long: 'C:\\Users\\RudolfBenner\\Desktop\\Marlin & Arduino Stuff\\Marlin-Conf\\MKS_GEN_L\\Marlin Bugfix 2.0.x\\Marlin\\.piolibdeps\\_tmp_installing-zzg8gz-package\\TMC26XStepper-c1921b4856a5ef4b659b661b8cb5dd56f3075e57\\examples\\TMC26XMotorTester\\processing\\TMC26XMotorTest'

============================================================

An unexpected error occurred. Further steps:

* Verify that you have the latest version of PlatformIO using
  `pip install -U platformio` command

* Try to find answer in FAQ Troubleshooting section
  http://docs.platformio.org/page/faq.html

* Report this problem to the developers
  https://github.com/platformio/platformio-core/issues

============================================================

Done.

**Comment by GhostlyCrowd** [comment]
You closed this so i assume you know whats the issue but just in case, it says it right in the end of your error log. your path is too long.  

"WindowsError: [Error 206] The filename or extension is too long:"
